name: buildAndPush

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:

  setup-ECR:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{vars.AWS_REGION}}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        

      - name: terraform init
        run: terraform init
        working-directory: ./terraform

      - name: Import Existing ECR (if any) # Check if ECR exists, then import to avoid recreation
        run: |
          if aws ecr describe-repositories --repository-names your-ecr-repo-name --region us-east-1 >/dev/null 2>&1; then
            echo "ECR exists, importing to state..."
            terraform import aws_ecr_repository.your_ecr_resource_name your-account-id.dkr.ecr.us-east-1.amazonaws.com/your-ecr-repo-name
          else
            echo "ECR doesn't exist yet, will create on apply."
          fi
        env:
          AWS_REGION: us-east-1
              
      - name: terraform apply
        id: ecr-repo
        run: |
          terraform fmt
          terraform apply -auto-approve
        working-directory: ./terraform

      - name: Cache Terraform providers
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

 

